window.esdocSearchIndex = [
  [
    "dom-renderer/source/dom/custominputevent.js~custominputevent",
    "class/source/DOM/CustomInputEvent.js~CustomInputEvent.html",
    "<span>CustomInputEvent</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/CustomInputEvent.js</span>",
    "class"
  ],
  [
    "dom-renderer/source/view/model.js~model",
    "class/source/view/Model.js~Model.html",
    "<span>Model</span> <span class=\"search-result-import-path\">dom-renderer/source/view/Model.js</span>",
    "class"
  ],
  [
    "dom-renderer/source/view/template.js~template",
    "class/source/view/Template.js~Template.html",
    "<span>Template</span> <span class=\"search-result-import-path\">dom-renderer/source/view/Template.js</span>",
    "class"
  ],
  [
    "dom-renderer/source/view/view.js~view",
    "class/source/view/View.js~View.html",
    "<span>View</span> <span class=\"search-result-import-path\">dom-renderer/source/view/View.js</span>",
    "class"
  ],
  [
    "dom-renderer/source/view/viewlist.js~viewlist",
    "class/source/view/ViewList.js~ViewList.html",
    "<span>ViewList</span> <span class=\"search-result-import-path\">dom-renderer/source/view/ViewList.js</span>",
    "class"
  ],
  [
    "dom-renderer/source/dom/parser.js~attributemap",
    "variable/index.html#static-variable-attributeMap",
    "<span>attributeMap</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/parser.js</span>",
    "variable"
  ],
  [
    "dom-renderer/source/dom/parser.js~attributeonly",
    "variable/index.html#static-variable-attributeOnly",
    "<span>attributeOnly</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/parser.js</span>",
    "variable"
  ],
  [
    "dom-renderer/source/dom/timer.js~debounce",
    "function/index.html#static-function-debounce",
    "<span>debounce</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/timer.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/timer.js~delay",
    "function/index.html#static-function-delay",
    "<span>delay</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/timer.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/manipulate.js~indexof",
    "function/index.html#static-function-indexOf",
    "<span>indexOf</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/manipulate.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/manipulate.js~insertto",
    "function/index.html#static-function-insertTo",
    "<span>insertTo</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/manipulate.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/object/array.js~insertableindexof",
    "function/index.html#static-function-insertableIndexOf",
    "<span>insertableIndexOf</span> <span class=\"search-result-import-path\">dom-renderer/source/object/array.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/object/array.js~likearray",
    "function/index.html#static-function-likeArray",
    "<span>likeArray</span> <span class=\"search-result-import-path\">dom-renderer/source/object/array.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/manipulate.js~makenode",
    "function/index.html#static-function-makeNode",
    "<span>makeNode</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/manipulate.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/timer.js~nexttick",
    "function/index.html#static-function-nextTick",
    "<span>nextTick</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/timer.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/parser.js~parsedom",
    "function/index.html#static-function-parseDOM",
    "<span>parseDOM</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/parser.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/parser.js~scandom",
    "function/index.html#static-function-scanDOM",
    "<span>scanDOM</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/parser.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/parser.js~stringifydom",
    "function/index.html#static-function-stringifyDOM",
    "<span>stringifyDOM</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/parser.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/timer.js~throttle",
    "function/index.html#static-function-throttle",
    "<span>throttle</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/timer.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/manipulate.js~valueof",
    "function/index.html#static-function-valueOf",
    "<span>valueOf</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/manipulate.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/parser.js~walkdom",
    "function/index.html#static-function-walkDOM",
    "<span>walkDOM</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/parser.js</span>",
    "function"
  ],
  [
    "dom-renderer/source/dom/custominputevent.js~watchinput",
    "function/index.html#static-function-watchInput",
    "<span>watchInput</span> <span class=\"search-result-import-path\">dom-renderer/source/DOM/CustomInputEvent.js</span>",
    "function"
  ],
  [
    "",
    "test-file/test/array.spec.js.html#lineNumber3",
    "Array utility methods",
    "test"
  ],
  [
    "likearray source/object/array.js~likearray,likearray",
    "test-file/test/array.spec.js.html#lineNumber7",
    "Array utility methods detects Array-like object",
    "test"
  ],
  [
    "insertableindexof source/object/array.js~insertableindexof,insertableindexof",
    "test-file/test/array.spec.js.html#lineNumber24",
    "Array utility methods gets insertable index of an Array",
    "test"
  ],
  [
    "view source/view/view.js~view,view",
    "test-file/test/View.spec.js.html#lineNumber19",
    "DOM View",
    "test"
  ],
  [
    "view#listen source/view/view.js~view#listen,view#listen",
    "test-file/test/View.spec.js.html#lineNumber179",
    "DOM View Auto update from Input fields",
    "test"
  ],
  [
    "view.instanceof source/view/view.js~view.instanceof,view.instanceof",
    "test-file/test/View.spec.js.html#lineNumber172",
    "DOM View Get the View of a Node",
    "test"
  ],
  [
    "view#parse view#addnode source/view/view.js~view#parse,view#parse source/view/view.js~view#addnode,view#addnode",
    "test-file/test/View.spec.js.html#lineNumber24",
    "DOM View Parsing",
    "test"
  ],
  [
    "view#render source/view/view.js~view#render,view#render",
    "test-file/test/View.spec.js.html#lineNumber49",
    "DOM View Rendering",
    "test"
  ],
  [
    "viewlist#render model#commit source/view/viewlist.js~viewlist#render,viewlist#render source/view/model.js~model#commit,model#commit",
    "test-file/test/View.spec.js.html#lineNumber154",
    "DOM View Sub view reusing",
    "test"
  ],
  [
    "viewlist#render source/view/viewlist.js~viewlist#render,viewlist#render",
    "test-file/test/View.spec.js.html#lineNumber107",
    "DOM View Updating",
    "test"
  ],
  [
    "view#parse view#listenkeys source/view/view.js~view#parse,view#parse source/view/view.js~view#listenkeys,view#listenkeys",
    "test-file/test/View.spec.js.html#lineNumber193",
    "DOM View re-parses a DOM tree",
    "test"
  ],
  [
    "",
    "test-file/test/manipulate.spec.js.html#lineNumber9",
    "DOM manipulation",
    "test"
  ],
  [
    "indexof source/dom/manipulate.js~indexof,indexof",
    "test-file/test/manipulate.spec.js.html#lineNumber13",
    "DOM manipulation gets the index of DOM nodes",
    "test"
  ],
  [
    "valueof source/dom/manipulate.js~valueof,valueof",
    "test-file/test/manipulate.spec.js.html#lineNumber48",
    "DOM manipulation gets values of Form fields",
    "test"
  ],
  [
    "insertto source/dom/manipulate.js~insertto,insertto",
    "test-file/test/manipulate.spec.js.html#lineNumber22",
    "DOM manipulation inserts Nodes to an Element by index",
    "test"
  ],
  [
    "",
    "test-file/test/parser.spec.js.html#lineNumber9",
    "DOM parser",
    "test"
  ],
  [
    "parsedom source/dom/parser.js~parsedom,parsedom",
    "test-file/test/parser.spec.js.html#lineNumber13",
    "DOM parser DOM parsing",
    "test"
  ],
  [
    "stringifydom source/dom/parser.js~stringifydom,stringifydom",
    "test-file/test/parser.spec.js.html#lineNumber26",
    "DOM parser DOM serialization",
    "test"
  ],
  [
    "walkdom source/dom/parser.js~walkdom,walkdom",
    "test-file/test/parser.spec.js.html#lineNumber35",
    "DOM parser DOM walking",
    "test"
  ],
  [
    "scandom source/dom/parser.js~scandom,scandom",
    "test-file/test/parser.spec.js.html#lineNumber76",
    "DOM parser Template scanning",
    "test"
  ],
  [
    "",
    "test-file/test/timer.spec.js.html#lineNumber5",
    "DOM timer",
    "test"
  ],
  [
    "debounce source/dom/timer.js~debounce,debounce",
    "test-file/test/timer.spec.js.html#lineNumber9",
    "DOM timer Debounce",
    "test"
  ],
  [
    "throttle source/dom/timer.js~throttle,throttle",
    "test-file/test/timer.spec.js.html#lineNumber27",
    "DOM timer Throttle",
    "test"
  ],
  [
    "model source/view/model.js~model,model",
    "test-file/test/Model.spec.js.html#lineNumber14",
    "Data model",
    "test"
  ],
  [
    "model#watch model#commit source/view/model.js~model#watch,model#watch source/view/model.js~model#commit,model#commit",
    "test-file/test/Model.spec.js.html#lineNumber51",
    "Data model Async update",
    "test"
  ],
  [
    "model#patch source/view/model.js~model#patch,model#patch",
    "test-file/test/Model.spec.js.html#lineNumber28",
    "Data model Full update",
    "test"
  ],
  [
    "model#patch source/view/model.js~model#patch,model#patch",
    "test-file/test/Model.spec.js.html#lineNumber41",
    "Data model Incremental update",
    "test"
  ],
  [
    "model#constructor model#valueof source/view/model.js~model#constructor,model#constructor source/view/model.js~model#valueof,model#valueof",
    "test-file/test/Model.spec.js.html#lineNumber19",
    "Data model Scope",
    "test"
  ],
  [
    "template source/view/template.js~template,template",
    "test-file/test/Template.spec.js.html#lineNumber11",
    "Template evaluator",
    "test"
  ],
  [
    "template#evaluate source/view/template.js~template#evaluate,template#evaluate",
    "test-file/test/Template.spec.js.html#lineNumber44",
    "Template evaluator Evaluating",
    "test"
  ],
  [
    "template#reset source/view/template.js~template#reset,template#reset",
    "test-file/test/Template.spec.js.html#lineNumber35",
    "Template evaluator No changing",
    "test"
  ],
  [
    "template#evaluatorof template#keysof source/view/template.js~template#evaluatorof,template#evaluatorof source/view/template.js~template#keysof,template#keysof",
    "test-file/test/Template.spec.js.html#lineNumber16",
    "Template evaluator Parsing",
    "test"
  ],
  [
    "viewlist source/view/viewlist.js~viewlist,viewlist",
    "test-file/test/ViewList.spec.js.html#lineNumber23",
    "View list",
    "test"
  ],
  [
    "viewlist#constructor source/view/viewlist.js~viewlist#constructor,viewlist#constructor",
    "test-file/test/ViewList.spec.js.html#lineNumber28",
    "View list creates a View list",
    "test"
  ],
  [
    "viewlist#tostring() viewlist#valueof() source/view/viewlist.js~viewlist#tostring,viewlist#tostring() source/view/viewlist.js~viewlist#valueof,viewlist#valueof()",
    "test-file/test/ViewList.spec.js.html#lineNumber81",
    "View list generates HTML source & JSON data",
    "test"
  ],
  [
    "viewlist#insert source/view/viewlist.js~viewlist#insert,viewlist#insert",
    "test-file/test/ViewList.spec.js.html#lineNumber66",
    "View list inserts an item",
    "test"
  ],
  [
    "viewlist#insert source/view/viewlist.js~viewlist#insert,viewlist#insert",
    "test-file/test/ViewList.spec.js.html#lineNumber38",
    "View list pushes an item",
    "test"
  ],
  [
    "viewlist#insert source/view/viewlist.js~viewlist#insert,viewlist#insert",
    "test-file/test/ViewList.spec.js.html#lineNumber52",
    "View list pushes another item",
    "test"
  ],
  [
    "viewlist#clear viewlist#render source/view/viewlist.js~viewlist#clear,viewlist#clear source/view/viewlist.js~viewlist#render,viewlist#render",
    "test-file/test/ViewList.spec.js.html#lineNumber98",
    "View list renders several items",
    "test"
  ],
  [
    "source/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "source/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "source/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "source/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "source/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "source/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "source/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "source/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "source/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "source/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "source/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "source/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "source/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "source/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "source/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "source/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "source/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "source/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "source/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "source/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "source/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "source/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "source/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "source/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "source/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "source/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "source/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "source/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "source/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "source/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "source/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "source/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "source/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "source/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "source/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "source/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "source/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "source/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "source/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "source/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "source/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "source/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "source/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "source/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "source/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "source/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "source/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "source/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "source/.external-ecmascript.js~String",
    "external"
  ],
  [
    "source/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "source/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "source/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "source/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "source/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "source/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "source/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "source/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "source/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "source/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "source/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "source/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "source/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "source/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "source/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "source/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "source/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "source/.external-ecmascript.js~function",
    "external"
  ],
  [
    "source/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "source/.external-ecmascript.js~null",
    "external"
  ],
  [
    "source/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "source/.external-ecmascript.js~number",
    "external"
  ],
  [
    "source/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "source/.external-ecmascript.js~object",
    "external"
  ],
  [
    "source/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "source/.external-ecmascript.js~string",
    "external"
  ],
  [
    "source/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "source/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "source/.external-webapi.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "source/.external-webapi.js~AudioContext",
    "external"
  ],
  [
    "source/.external-webapi.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "source/.external-webapi.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "source/.external-webapi.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "source/.external-webapi.js~DocumentFragment",
    "external"
  ],
  [
    "source/.external-webapi.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "source/.external-webapi.js~Element",
    "external"
  ],
  [
    "source/.external-webapi.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "source/.external-webapi.js~Event",
    "external"
  ],
  [
    "source/.external-webapi.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "source/.external-webapi.js~Node",
    "external"
  ],
  [
    "source/.external-webapi.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "source/.external-webapi.js~NodeList",
    "external"
  ],
  [
    "source/.external-webapi.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "source/.external-webapi.js~XMLHttpRequest",
    "external"
  ],
  [
    "source/dom/custominputevent.js",
    "file/source/DOM/CustomInputEvent.js.html",
    "source/DOM/CustomInputEvent.js",
    "file"
  ],
  [
    "source/dom/custominputevent.js~custominputevent#target",
    "class/source/DOM/CustomInputEvent.js~CustomInputEvent.html#instance-get-target",
    "source/DOM/CustomInputEvent.js~CustomInputEvent#target",
    "member"
  ],
  [
    "source/dom/manipulate.js",
    "file/source/DOM/manipulate.js.html",
    "source/DOM/manipulate.js",
    "file"
  ],
  [
    "source/dom/parser.js",
    "file/source/DOM/parser.js.html",
    "source/DOM/parser.js",
    "file"
  ],
  [
    "source/dom/polyfill.js",
    "file/source/DOM/polyfill.js.html",
    "source/DOM/polyfill.js",
    "file"
  ],
  [
    "source/dom/timer.js",
    "file/source/DOM/timer.js.html",
    "source/DOM/timer.js",
    "file"
  ],
  [
    "source/index.js",
    "file/source/index.js.html",
    "source/index.js",
    "file"
  ],
  [
    "source/object/array.js",
    "file/source/object/array.js.html",
    "source/object/array.js",
    "file"
  ],
  [
    "source/view/model.js",
    "file/source/view/Model.js.html",
    "source/view/Model.js",
    "file"
  ],
  [
    "source/view/model.js~model#[cache_data]",
    "class/source/view/Model.js~Model.html#instance-member-[cache_data]",
    "source/view/Model.js~Model#[cache_data]",
    "member"
  ],
  [
    "source/view/model.js~model#commit",
    "class/source/view/Model.js~Model.html#instance-method-commit",
    "source/view/Model.js~Model#commit",
    "method"
  ],
  [
    "source/view/model.js~model#constructor",
    "class/source/view/Model.js~Model.html#instance-constructor-constructor",
    "source/view/Model.js~Model#constructor",
    "method"
  ],
  [
    "source/view/model.js~model#data",
    "class/source/view/Model.js~Model.html#instance-get-data",
    "source/view/Model.js~Model#data",
    "member"
  ],
  [
    "source/view/model.js~model#patch",
    "class/source/view/Model.js~Model.html#instance-method-patch",
    "source/view/Model.js~Model#patch",
    "method"
  ],
  [
    "source/view/model.js~model#scope",
    "class/source/view/Model.js~Model.html#instance-get-scope",
    "source/view/Model.js~Model#scope",
    "member"
  ],
  [
    "source/view/model.js~model#valueof",
    "class/source/view/Model.js~Model.html#instance-method-valueOf",
    "source/view/Model.js~Model#valueOf",
    "method"
  ],
  [
    "source/view/model.js~model#watch",
    "class/source/view/Model.js~Model.html#instance-method-watch",
    "source/view/Model.js~Model#watch",
    "method"
  ],
  [
    "source/view/template.js",
    "file/source/view/Template.js.html",
    "source/view/Template.js",
    "file"
  ],
  [
    "source/view/template.js~template#[template_raw]",
    "class/source/view/Template.js~Template.html#instance-member-[template_raw]",
    "source/view/Template.js~Template#[template_raw]",
    "member"
  ],
  [
    "source/view/template.js~template#[template_value]",
    "class/source/view/Template.js~Template.html#instance-member-[template_value]",
    "source/view/Template.js~Template#[template_value]",
    "member"
  ],
  [
    "source/view/template.js~template#constructor",
    "class/source/view/Template.js~Template.html#instance-constructor-constructor",
    "source/view/Template.js~Template#constructor",
    "method"
  ],
  [
    "source/view/template.js~template#evaluate",
    "class/source/view/Template.js~Template.html#instance-method-evaluate",
    "source/view/Template.js~Template#evaluate",
    "method"
  ],
  [
    "source/view/template.js~template#evaluatorof",
    "class/source/view/Template.js~Template.html#instance-method-evaluatorOf",
    "source/view/Template.js~Template#evaluatorOf",
    "method"
  ],
  [
    "source/view/template.js~template#keysof",
    "class/source/view/Template.js~Template.html#instance-method-keysOf",
    "source/view/Template.js~Template#keysOf",
    "method"
  ],
  [
    "source/view/template.js~template#reset",
    "class/source/view/Template.js~Template.html#instance-method-reset",
    "source/view/Template.js~Template#reset",
    "method"
  ],
  [
    "source/view/template.js~template#tostring",
    "class/source/view/Template.js~Template.html#instance-method-toString",
    "source/view/Template.js~Template#toString",
    "method"
  ],
  [
    "source/view/template.js~template#valueof",
    "class/source/view/Template.js~Template.html#instance-method-valueOf",
    "source/view/Template.js~Template#valueOf",
    "method"
  ],
  [
    "source/view/view.js",
    "file/source/view/View.js.html",
    "source/view/View.js",
    "file"
  ],
  [
    "source/view/view.js~view#addnode",
    "class/source/view/View.js~View.html#instance-method-addNode",
    "source/view/View.js~View#addNode",
    "method"
  ],
  [
    "source/view/view.js~view#clone",
    "class/source/view/View.js~View.html#instance-method-clone",
    "source/view/View.js~View#clone",
    "method"
  ],
  [
    "source/view/view.js~view#constructor",
    "class/source/view/View.js~View.html#instance-constructor-constructor",
    "source/view/View.js~View#constructor",
    "method"
  ],
  [
    "source/view/view.js~view#destroy",
    "class/source/view/View.js~View.html#instance-method-destroy",
    "source/view/View.js~View#destroy",
    "method"
  ],
  [
    "source/view/view.js~view#listen",
    "class/source/view/View.js~View.html#instance-method-listen",
    "source/view/View.js~View#listen",
    "method"
  ],
  [
    "source/view/view.js~view#listenkeys",
    "class/source/view/View.js~View.html#instance-get-listenKeys",
    "source/view/View.js~View#listenKeys",
    "member"
  ],
  [
    "source/view/view.js~view#parse",
    "class/source/view/View.js~View.html#instance-method-parse",
    "source/view/View.js~View#parse",
    "method"
  ],
  [
    "source/view/view.js~view#render",
    "class/source/view/View.js~View.html#instance-method-render",
    "source/view/View.js~View#render",
    "method"
  ],
  [
    "source/view/view.js~view#root",
    "class/source/view/View.js~View.html#instance-get-root",
    "source/view/View.js~View#root",
    "member"
  ],
  [
    "source/view/view.js~view#tostring",
    "class/source/view/View.js~View.html#instance-method-toString",
    "source/view/View.js~View#toString",
    "method"
  ],
  [
    "source/view/view.js~view#topnodes",
    "class/source/view/View.js~View.html#instance-get-topNodes",
    "source/view/View.js~View#topNodes",
    "member"
  ],
  [
    "source/view/view.js~view.findtemplate",
    "class/source/view/View.js~View.html#static-method-findTemplate",
    "source/view/View.js~View.findTemplate",
    "method"
  ],
  [
    "source/view/view.js~view.gettemplate",
    "class/source/view/View.js~View.html#static-method-getTemplate",
    "source/view/View.js~View.getTemplate",
    "method"
  ],
  [
    "source/view/view.js~view.instanceof",
    "class/source/view/View.js~View.html#static-method-instanceOf",
    "source/view/View.js~View.instanceOf",
    "method"
  ],
  [
    "source/view/viewlist.js",
    "file/source/view/ViewList.js.html",
    "source/view/ViewList.js",
    "file"
  ],
  [
    "source/view/viewlist.js~viewlist#[child_offset]",
    "class/source/view/ViewList.js~ViewList.html#instance-member-[child_offset]",
    "source/view/ViewList.js~ViewList#[child_offset]",
    "member"
  ],
  [
    "source/view/viewlist.js~viewlist#[template]",
    "class/source/view/ViewList.js~ViewList.html#instance-member-[template]",
    "source/view/ViewList.js~ViewList#[template]",
    "member"
  ],
  [
    "source/view/viewlist.js~viewlist#clear",
    "class/source/view/ViewList.js~ViewList.html#instance-method-clear",
    "source/view/ViewList.js~ViewList#clear",
    "method"
  ],
  [
    "source/view/viewlist.js~viewlist#constructor",
    "class/source/view/ViewList.js~ViewList.html#instance-constructor-constructor",
    "source/view/ViewList.js~ViewList#constructor",
    "method"
  ],
  [
    "source/view/viewlist.js~viewlist#data",
    "class/source/view/ViewList.js~ViewList.html#instance-get-data",
    "source/view/ViewList.js~ViewList#data",
    "member"
  ],
  [
    "source/view/viewlist.js~viewlist#insert",
    "class/source/view/ViewList.js~ViewList.html#instance-method-insert",
    "source/view/ViewList.js~ViewList#insert",
    "method"
  ],
  [
    "source/view/viewlist.js~viewlist#length",
    "class/source/view/ViewList.js~ViewList.html#instance-set-length",
    "source/view/ViewList.js~ViewList#length",
    "member"
  ],
  [
    "source/view/viewlist.js~viewlist#name",
    "class/source/view/ViewList.js~ViewList.html#instance-get-name",
    "source/view/ViewList.js~ViewList#name",
    "member"
  ],
  [
    "source/view/viewlist.js~viewlist#render",
    "class/source/view/ViewList.js~ViewList.html#instance-method-render",
    "source/view/ViewList.js~ViewList#render",
    "method"
  ],
  [
    "source/view/viewlist.js~viewlist#root",
    "class/source/view/ViewList.js~ViewList.html#instance-get-root",
    "source/view/ViewList.js~ViewList#root",
    "member"
  ],
  [
    "source/view/viewlist.js~viewlist#tostring",
    "class/source/view/ViewList.js~ViewList.html#instance-method-toString",
    "source/view/ViewList.js~ViewList#toString",
    "method"
  ],
  [
    "source/view/viewlist.js~viewlist#valueof",
    "class/source/view/ViewList.js~ViewList.html#instance-method-valueOf",
    "source/view/ViewList.js~ViewList#valueOf",
    "method"
  ],
  [
    "source/view/viewlist.js~viewlist.instanceof",
    "class/source/view/ViewList.js~ViewList.html#static-method-instanceOf",
    "source/view/ViewList.js~ViewList.instanceOf",
    "method"
  ],
  [
    "test/model.spec.js",
    "test-file/test/Model.spec.js.html",
    "test/Model.spec.js",
    "testFile"
  ],
  [
    "test/template.spec.js",
    "test-file/test/Template.spec.js.html",
    "test/Template.spec.js",
    "testFile"
  ],
  [
    "test/view.spec.js",
    "test-file/test/View.spec.js.html",
    "test/View.spec.js",
    "testFile"
  ],
  [
    "test/viewlist.spec.js",
    "test-file/test/ViewList.spec.js.html",
    "test/ViewList.spec.js",
    "testFile"
  ],
  [
    "test/array.spec.js",
    "test-file/test/array.spec.js.html",
    "test/array.spec.js",
    "testFile"
  ],
  [
    "test/manipulate.spec.js",
    "test-file/test/manipulate.spec.js.html",
    "test/manipulate.spec.js",
    "testFile"
  ],
  [
    "test/parser.spec.js",
    "test-file/test/parser.spec.js.html",
    "test/parser.spec.js",
    "testFile"
  ],
  [
    "test/timer.spec.js",
    "test-file/test/timer.spec.js.html",
    "test/timer.spec.js",
    "testFile"
  ]
]